In [17]:
print("hello")

hello


**Numpy array vs python lists**

In [18]:
#speed
#list
a = [i for i in range(10000000)]
b = [i for i in range(10000000,20000000)]

c = []
import time

start = time.time()
for i in range(len(a)):
  c.append(a[i] + b[i])
print(time.time()-start)

2.552593946456909


In [19]:
#speed
#numpy
import numpy as np
a = np.arange(10000000)
b = np.arange(10000000,20000000)

start = time.time()
c = a + b
print(time.time()-start)

0.28632164001464844


In [20]:
#memory
#list
a = [i for i in range(10000000)]
import sys

sys.getsizeof(a)

89095160

In [21]:
a = np.arange(10000000,dtype=np.int8)
sys.getsizeof(a)

10000112

**Advanced Indexing**

In [22]:
#Normal Indexing and slicing

a = np.arange(24).reshape(6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [25]:
#Fancing Indexing

print(a)

print(a[[0,2,3]])

print(a[:,[0,2,3]])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[ 0  1  2  3]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]
 [12 14 15]
 [16 18 19]
 [20 22 23]]


In [24]:
#Boolean Indexing