In [ ]:
print("hello")

hello


**np.sort**

Return a sorted copy of array

In [2]:
#code
import numpy as np
a = np.random.randint(1,100,15)
a

array([39, 10,  8, 41, 14, 43, 77, 66, 33, 19, 63, 83, 16, 25, 38])

In [3]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[60, 86,  4, 31],
       [93, 66, 65, 96],
       [69, 64,  1, 59],
       [ 8, 91, 38, 83],
       [42, 38, 17,  6],
       [64, 69, 24, 46]])

In [6]:
np.sort(a)

#reverse sort
np.sort(a)[::-1]

array([83, 77, 66, 63, 43, 41, 39, 38, 33, 25, 19, 16, 14, 10,  8])

In [5]:
np.sort(b)

array([[ 4, 31, 60, 86],
       [65, 66, 93, 96],
       [ 1, 59, 64, 69],
       [ 8, 38, 83, 91],
       [ 6, 17, 38, 42],
       [24, 46, 64, 69]])

**np.append**

The numpy.append() appends values along the mentioned axis at the end of the array

In [7]:
#code
np.append(a,200)

array([ 39,  10,   8,  41,  14,  43,  77,  66,  33,  19,  63,  83,  16,
        25,  38, 200])

In [8]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[60., 86.,  4., 31.,  1.],
       [93., 66., 65., 96.,  1.],
       [69., 64.,  1., 59.,  1.],
       [ 8., 91., 38., 83.,  1.],
       [42., 38., 17.,  6.,  1.],
       [64., 69., 24., 46.,  1.]])

**np.concatenate**

numpy.concatenate() function concatenate a sequence of array along as existing axis.

In [9]:
#code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [11]:
np.concatenate((c,d),axis=0)

np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

**np.unique**

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

In [12]:
#code
e = np.array([1,1,2,2,3,4,4,5,5,6,7,7])

np.unique(e)

array([1, 2, 3, 4, 5, 6, 7])

**np.expand_dims**

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array.

In [15]:
#code
a
a.shape

(15,)

In [18]:
np.expand_dims(a,axis=0)
# 1 row 15 cols
np.expand_dims(a,axis=0).shape

(1, 15)

In [21]:
np.expand_dims(a,axis=1)
# 15 row 1 cols
np.expand_dims(a,axis=1).shape

(15, 1)

**np.where**