In [58]:
print("hello")

hello


**What is Numpy?**

**Creating Numpy Arrays**

In [59]:
#np.array
import numpy as np
np.array([1,2,3,4])
# a = np.array([1,2,3,4])
# print(type(a))

array([1, 2, 3, 4])

In [60]:
# 2D and 3D
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [61]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [62]:
#dtype
np.array([1,2,3],dtype=float)
# np.array([1,2,3],dtype=bool)

array([1., 2., 3.])

In [63]:
#np.arange()
# np.arange(1,11)
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [64]:
# with reshape
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [65]:
#np.ones and np.zeros
# np.ones -> 1
np.ones((3,4))

#np.zeros -> 0
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [66]:
#np.random
np.random.random((3,4))

array([[0.04878422, 0.64047561, 0.31526171, 0.47283988],
       [0.38567269, 0.70462066, 0.48212335, 0.91354656],
       [0.99226339, 0.44021334, 0.4441108 , 0.62041698]])

In [67]:
#np.linspace
np.linspace(-10,10,11)

array([-10.,  -8.,  -6.,  -4.,  -2.,   0.,   2.,   4.,   6.,   8.,  10.])

In [68]:
#np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**Array Attributes**

In [69]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [70]:
#ndim
# its give the dimension
a3.ndim

3

In [71]:
#shape
# show the shape with in one row there are 10 items | cols
a1.shape

# show the shape with 3 row and 4 cols
a2.shape

# show the shape with [[[1,2],[3,4]],[[5,6],[7,8]]]
a3.shape
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [72]:
#size
a3.size

8

In [73]:
#itemsize
a1.itemsize

a3.itemsize

8

In [74]:
#dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64


**Changing Datatype**

In [75]:
#astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

**Array Operations**

In [76]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [77]:
#scalar operations

#arithmetic
a1 = a1 * 2

In [78]:
#relational
# a1 > 5

a1 == 16

array([[False, False, False, False],
       [False, False, False, False],
       [ True, False, False, False]])

In [79]:
#vector operations -> means operations between two np array

#arithmetic
a1 * a2

array([[  0,  26,  56,  90],
       [128, 170, 216, 266],
       [320, 378, 440, 506]])

In [80]:
#max/min/sum/prod
#   0 -> col and 1 -> row

np.min(a1)
np.max(a1)
np.sum(a1)
np.prod(a1)

np.max(a1,axis=0)


array([16, 18, 20, 22])

In [81]:
#mean/median/std/var
np.mean(a1)

np.float64(11.0)

In [82]:
#trigonometric functions
np.sin(a1)

array([[ 0.        ,  0.90929743, -0.7568025 , -0.2794155 ],
       [ 0.98935825, -0.54402111, -0.53657292,  0.99060736],
       [-0.28790332, -0.75098725,  0.91294525, -0.00885131]])

In [83]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [84]:
# log and exponents
np.exp(a1)

array([[1.00000000e+00, 7.38905610e+00, 5.45981500e+01, 4.03428793e+02],
       [2.98095799e+03, 2.20264658e+04, 1.62754791e+05, 1.20260428e+06],
       [8.88611052e+06, 6.56599691e+07, 4.85165195e+08, 3.58491285e+09]])

In [85]:
#round/floor/ceil
np.round(np.random.random((2,3))*100)

array([[19., 67., 76.],
       [58., 76., 97.]])

**Indexing and Slicing**

In [87]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [88]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [89]:
a1[-1]

np.int64(9)

In [90]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [91]:
# get 6 from a2
a2[1,2]

np.int64(6)

In [92]:
# get 11 from a2
a2[2,3]

np.int64(11)

In [93]:
# get 4 from a2
a2[1,0]

np.int64(4)

In [94]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [95]:
#get 5 from a3

a3[1,0,1]

np.int64(5)

In [96]:
# get 2 from a3

a3[0,1,0]

np.int64(2)

In [97]:
# get 0 from a3

a3[0,0,0]

np.int64(0)

**Slicing**

In [98]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [99]:
# get 2,3,4 from a1

a1[2:5]

array([2, 3, 4])

In [100]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [103]:
# get 1 row from a2

# a2[:1]

a2[0,:]

array([0, 1, 2, 3])

In [104]:
# get 3 col from a2

a2[:,2]

array([ 2,  6, 10])

In [105]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [108]:
# get 5,6 and 9,10 from a2

a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [112]:
# get 0,3 and 8,11 from a2

a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [113]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [115]:
# get 9,11 from a2

a2[-1,1::2]

array([ 9, 11])

In [121]:
# get 4,7 from a2

a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [122]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [123]:
# '''
# [[ 9, 10, 11],
#         [12, 13, 14],
#         [15, 16, 17]],
# ''' get this from a3

a3[1]


array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [124]:
# '''
# [[ 0,  1,  2],
#         [ 3,  4,  5],
#         [ 6,  7,  8]],
# [[18, 19, 20],
#         [21, 22, 23],
#         [24, 25, 26]]
# ''' get this from a3

a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])