In [ ]:
print("hello")

hello


**What is Numpy?**

**Creating Numpy Arrays**

In [6]:
#np.array
import numpy as np
np.array([1,2,3,4])
# a = np.array([1,2,3,4])
# print(type(a))

array([1, 2, 3, 4])

In [7]:
# 2D and 3D
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [8]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [11]:
#dtype
np.array([1,2,3],dtype=float)
# np.array([1,2,3],dtype=bool)

array([1., 2., 3.])

In [14]:
#np.arange()
# np.arange(1,11)
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [15]:
# with reshape
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [19]:
#np.ones and np.zeros
# np.ones -> 1
np.ones((3,4))

#np.zeros -> 0
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
#np.random
np.random.random((3,4))

array([[0.572527  , 0.26531488, 0.20402662, 0.02371985],
       [0.49209554, 0.73284027, 0.30437983, 0.51274763],
       [0.7116708 , 0.82376255, 0.29320491, 0.96368333]])

In [23]:
#np.linspace
np.linspace(-10,10,11)

array([-10.,  -8.,  -6.,  -4.,  -2.,   0.,   2.,   4.,   6.,   8.,  10.])

In [26]:
#np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**Array Attributes**

In [46]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [41]:
#ndim
# its give the dimension
a3.ndim

3

In [43]:
#shape
# show the shape with in one row there are 10 items | cols
a1.shape

# show the shape with 3 row and 4 cols
a2.shape

# show the shape with [[[1,2],[3,4]],[[5,6],[7,8]]]
a3.shape
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [44]:
#size
a3.size

8

In [49]:
#itemsize
a1.itemsize

a3.itemsize

8

In [50]:
#dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64


**Changing Datatype**