In [2]:
print("hello")

hello


**What is Numpy?**

**Creating Numpy Arrays**

In [3]:
#np.array
import numpy as np
np.array([1,2,3,4])
# a = np.array([1,2,3,4])
# print(type(a))

array([1, 2, 3, 4])

In [4]:
# 2D and 3D
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [5]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [6]:
#dtype
np.array([1,2,3],dtype=float)
# np.array([1,2,3],dtype=bool)

array([1., 2., 3.])

In [7]:
#np.arange()
# np.arange(1,11)
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [8]:
# with reshape
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [9]:
#np.ones and np.zeros
# np.ones -> 1
np.ones((3,4))

#np.zeros -> 0
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
#np.random
np.random.random((3,4))

array([[0.66150773, 0.83936662, 0.32012595, 0.85763401],
       [0.551007  , 0.6026805 , 0.57017529, 0.95918037],
       [0.76109168, 0.12501613, 0.24362956, 0.66441643]])

In [11]:
#np.linspace
np.linspace(-10,10,11)

array([-10.,  -8.,  -6.,  -4.,  -2.,   0.,   2.,   4.,   6.,   8.,  10.])

In [12]:
#np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**Array Attributes**

In [13]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [14]:
#ndim
# its give the dimension
a3.ndim

3

In [15]:
#shape
# show the shape with in one row there are 10 items | cols
a1.shape

# show the shape with 3 row and 4 cols
a2.shape

# show the shape with [[[1,2],[3,4]],[[5,6],[7,8]]]
a3.shape
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [16]:
#size
a3.size

8

In [17]:
#itemsize
a1.itemsize

a3.itemsize

8

In [18]:
#dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64


**Changing Datatype**

In [19]:
#astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

**Array Operations**

In [20]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [21]:
#scalar operations

#arithmetic
a1 = a1 * 2

In [22]:
#relational
# a1 > 5

a1 == 16

array([[False, False, False, False],
       [False, False, False, False],
       [ True, False, False, False]])

In [23]:
#vector operations -> means operations between two np array

#arithmetic
a1 * a2

array([[  0,  26,  56,  90],
       [128, 170, 216, 266],
       [320, 378, 440, 506]])

In [24]:
#max/min/sum/prod
#   0 -> col and 1 -> row

np.min(a1)
np.max(a1)
np.sum(a1)
np.prod(a1)

np.max(a1,axis=0)


array([16, 18, 20, 22])

In [25]:
#mean/median/std/var
np.mean(a1)

np.float64(11.0)

In [26]:
#trigonometric functions
np.sin(a1)

array([[ 0.        ,  0.90929743, -0.7568025 , -0.2794155 ],
       [ 0.98935825, -0.54402111, -0.53657292,  0.99060736],
       [-0.28790332, -0.75098725,  0.91294525, -0.00885131]])

In [27]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [28]:
# log and exponents
np.exp(a1)

array([[1.00000000e+00, 7.38905610e+00, 5.45981500e+01, 4.03428793e+02],
       [2.98095799e+03, 2.20264658e+04, 1.62754791e+05, 1.20260428e+06],
       [8.88611052e+06, 6.56599691e+07, 4.85165195e+08, 3.58491285e+09]])

In [29]:
#round/floor/ceil
np.round(np.random.random((2,3))*100)

array([[18., 98., 97.],
       [70., 58., 29.]])

**Indexing and Slicing**

In [30]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [31]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
a1[-1]

np.int64(9)

In [33]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [34]:
# get 6 from a2
a2[1,2]

np.int64(6)

In [35]:
# get 11 from a2
a2[2,3]

np.int64(11)

In [36]:
# get 4 from a2
a2[1,0]

np.int64(4)

In [37]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [38]:
#get 5 from a3

a3[1,0,1]

np.int64(5)

In [39]:
# get 2 from a3

a3[0,1,0]

np.int64(2)

In [40]:
# get 0 from a3

a3[0,0,0]

np.int64(0)

**Slicing**

In [41]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
# get 2,3,4 from a1

a1[2:5]

array([2, 3, 4])

In [43]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [44]:
# get 1 row from a2

# a2[:1]

a2[0,:]

array([0, 1, 2, 3])

In [45]:
# get 3 col from a2

a2[:,2]

array([ 2,  6, 10])

In [46]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [47]:
# get 5,6 and 9,10 from a2

a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [48]:
# get 0,3 and 8,11 from a2

a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [49]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [50]:
# get 9,11 from a2

a2[-1,1::2]

array([ 9, 11])

In [51]:
# get 4,7 from a2

a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [52]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [53]:
# '''
# [[ 9, 10, 11],
#         [12, 13, 14],
#         [15, 16, 17]],
# ''' get this from a3

a3[1]


array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [54]:
# '''
# [[ 0,  1,  2],
#         [ 3,  4,  5],
#         [ 6,  7,  8]],
# [[18, 19, 20],
#         [21, 22, 23],
#         [24, 25, 26]]
# ''' get this from a3

a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [57]:
# get [ 3,  4,  5] from a3

a3[0,1]

array([3, 4, 5])

In [58]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [64]:
# get 10,13,16 from a3

a3[1,:,1]

array([10, 13, 16])

In [67]:
# get 22,23,25,26 from a3

a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [72]:
# get 0,2,18,20 from a3

a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

**Iterating**

In [77]:
a1
for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [78]:
a2
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [79]:
a3
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [81]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


**Reshaping**

In [82]:
#reshape

In [86]:
#Transpose -> used for convert row to col and col to row

#syntax 1
np.transpose(a2)

#syntax 2
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [88]:
#ravel -> convert array into 1d array
a2.ravel()

a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

**Stacking**

In [96]:
#horizontal stacking -> row is same | col is stack
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

print(a4) # row = 3 || cols = 4
print(a5) # row = 3 || cols = 4

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [97]:
np.hstack((a4,a5)) # row = 3 || cols = 8

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [ ]:
#vertical stacking -> row is stack | col is same