In [ ]:
print("hello")

hello


**np.sort**

Return a sorted copy of array

In [2]:
#code
import numpy as np
a = np.random.randint(1,100,15)
a

array([39, 10,  8, 41, 14, 43, 77, 66, 33, 19, 63, 83, 16, 25, 38])

In [3]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[60, 86,  4, 31],
       [93, 66, 65, 96],
       [69, 64,  1, 59],
       [ 8, 91, 38, 83],
       [42, 38, 17,  6],
       [64, 69, 24, 46]])

In [6]:
np.sort(a)

#reverse sort
np.sort(a)[::-1]

array([83, 77, 66, 63, 43, 41, 39, 38, 33, 25, 19, 16, 14, 10,  8])

In [5]:
np.sort(b)

array([[ 4, 31, 60, 86],
       [65, 66, 93, 96],
       [ 1, 59, 64, 69],
       [ 8, 38, 83, 91],
       [ 6, 17, 38, 42],
       [24, 46, 64, 69]])

**np.append**

The numpy.append() appends values along the mentioned axis at the end of the array

In [7]:
#code
np.append(a,200)

array([ 39,  10,   8,  41,  14,  43,  77,  66,  33,  19,  63,  83,  16,
        25,  38, 200])

In [8]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[60., 86.,  4., 31.,  1.],
       [93., 66., 65., 96.,  1.],
       [69., 64.,  1., 59.,  1.],
       [ 8., 91., 38., 83.,  1.],
       [42., 38., 17.,  6.,  1.],
       [64., 69., 24., 46.,  1.]])

**np.concatenate**

numpy.concatenate() function concatenate a sequence of array along as existing axis.

In [9]:
#code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [11]:
np.concatenate((c,d),axis=0)

np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

**np.unique**

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

In [12]:
#code
e = np.array([1,1,2,2,3,4,4,5,5,6,7,7])

np.unique(e)

array([1, 2, 3, 4, 5, 6, 7])

**np.expand_dims**

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array.

In [15]:
#code
a
a.shape

(15,)

In [18]:
np.expand_dims(a,axis=0)
# 1 row 15 cols
np.expand_dims(a,axis=0).shape

(1, 15)

In [21]:
np.expand_dims(a,axis=1)
# 15 row 1 cols
np.expand_dims(a,axis=1).shape

(15, 1)

**np.where**

The numpy.where() functions return the indexs of elements in an input array where the given condition is satisfied.

In [24]:
a

array([39, 10,  8, 41, 14, 43, 77, 66, 33, 19, 63, 83, 16, 25, 38])

In [27]:
# find all indexe with value greater then 50

np.where(a > 50)

a[np.where(a>50)]


array([77, 66, 63, 83])

In [28]:
# replace all values > 50 with 0

np.where(a>50,0,a)

array([39, 10,  8, 41, 14, 43,  0,  0, 33, 19,  0,  0, 16, 25, 38])

In [29]:
np.where(a%2==0,0,a)

array([39,  0,  0, 41,  0, 43, 77,  0, 33, 19, 63, 83,  0, 25,  0])

**np.argmax**

The numpy.argmax() function returns indexs of the max element of the array in a particular axis.

In [30]:
#code
a

array([39, 10,  8, 41, 14, 43, 77, 66, 33, 19, 63, 83, 16, 25, 38])

In [33]:
print(np.argmax(a)) # at postions of index

11


In [34]:
b

array([[60, 86,  4, 31],
       [93, 66, 65, 96],
       [69, 64,  1, 59],
       [ 8, 91, 38, 83],
       [42, 38, 17,  6],
       [64, 69, 24, 46]])

In [37]:
np.argmax(b,axis=0) # cols

array([1, 3, 1, 1])

In [39]:
np.argmax(b,axis=1) # row

array([1, 3, 0, 1, 0, 1])

In [40]:
# np.argmin

a

array([39, 10,  8, 41, 14, 43, 77, 66, 33, 19, 63, 83, 16, 25, 38])

In [42]:
np.argmin(a)

np.int64(2)

**np.cumsum**

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

In [47]:
#np.cumsum
a

array([39, 10,  8, 41, 14, 43, 77, 66, 33, 19, 63, 83, 16, 25, 38])

In [45]:
np.cumsum(a)

array([ 39,  49,  57,  98, 112, 155, 232, 298, 331, 350, 413, 496, 512,
       537, 575])

In [48]:
b

array([[60, 86,  4, 31],
       [93, 66, 65, 96],
       [69, 64,  1, 59],
       [ 8, 91, 38, 83],
       [42, 38, 17,  6],
       [64, 69, 24, 46]])

In [50]:
np.cumsum(b,axis=0) # cols wise

array([[ 60,  86,   4,  31],
       [153, 152,  69, 127],
       [222, 216,  70, 186],
       [230, 307, 108, 269],
       [272, 345, 125, 275],
       [336, 414, 149, 321]])

In [51]:
np.cumsum(b,axis=1) # row wise

array([[ 60, 146, 150, 181],
       [ 93, 159, 224, 320],
       [ 69, 133, 134, 193],
       [  8,  99, 137, 220],
       [ 42,  80,  97, 103],
       [ 64, 133, 157, 203]])

In [52]:
#np.cumprod
a

array([39, 10,  8, 41, 14, 43, 77, 66, 33, 19, 63, 83, 16, 25, 38])

In [53]:
np.cumprod(a)

array([                  39,                  390,                 3120,
                     127920,              1790880,             77007840,
                 5929603680,         391353842880,       12914676815040,
            245378859485760,    15458868147602880,  1283086056251039040,
        2082632826307073024, -3274411563451829248,  4699569104797349888])

In [54]:
b

array([[60, 86,  4, 31],
       [93, 66, 65, 96],
       [69, 64,  1, 59],
       [ 8, 91, 38, 83],
       [42, 38, 17,  6],
       [64, 69, 24, 46]])

In [55]:
np.cumsum(b,axis=1)

array([[ 60, 146, 150, 181],
       [ 93, 159, 224, 320],
       [ 69, 133, 134, 193],
       [  8,  99, 137, 220],
       [ 42,  80,  97, 103],
       [ 64, 133, 157, 203]])